backend:
  name: github
  repo: UTW-web/Travel
  branch: main
  client_id: Ov23lisS9eDPOxjdJHug

publish_mode: simple

media_folder: "Slike"
public_folder: "/Slike"

collections:
  - name: "pages"
    label: "Strani"
    files:

      - label: "Domov"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Glavni naslov", name: "title", widget: "string" }
          - { label: "Podnaslov", name: "subtitle", widget: "string" }
          - { label: "Besedilo", name: "body", widget: "markdown" }

      - label: "O meni"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Naslov", name: "title", widget: "string" }
          - { label: "Besedilo", name: "body", widget: "markdown" }

      - label: "Sunrise"
        name: "sunrise"
        file: "content/sunrise.md"
        fields:
          - { label: "Naslov", name: "title", widget: "string" }
          - { label: "Besedilo", name: "body", widget: "markdown" }

      - label: "Sunset"
        name: "sunset"
        file: "content/sunset.md"
        fields:
          - { label: "Naslov", name: "title", widget: "string" }
          - { label: "Besedilo", name: "body", widget: "markdown" }
